name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Prepare west workspace
        run: |
          rm -rf west-workspace

      - name: West init (using this config repo)
        run: |
          west init -l config west-workspace
          west update

      - name: Build firmware
        run: |
          west build -d build -b nice_nano_v2 app
